apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-email-config
  namespace: default
stringData:
  alertmanager.yaml: |
    global:
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_from: 'your-email@gmail.com'
      smtp_auth_username: 'your-email@gmail.com'
      smtp_auth_password: 'your-password'
      smtp_require_tls: true

    route:
      receiver: 'email-notifications'

    receivers:
      - name: 'email-notifications'
        email_configs:
          - to: 'receiver-email@gmail.com'
            send_resolved: true
