apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: register-app-alerts
  labels:
    app: register-app
    release: prometheus
spec:
  groups:
    - name: register-app-alerts
      rules:

        # Alert when all pods are down
        - alert: RegisterAppDown
          expr: kube_deployment_status_replicas_available{deployment="register-app-deployment"} == 0
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "Register App is DOWN"
            description: "No available replicas for more than 1 minute."

        # Alert when a pod keeps restarting
        - alert: RegisterAppCrashLooping
          expr: rate(kube_pod_container_status_restarts_total{pod=~"register-app-deployment-.*"}[10m]) > 0
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "Register App pod is restarting"
            description: "Pod {{ $labels.pod }} has been restarting frequently."

        # Alert when CPU usage is too high
        - alert: RegisterAppHighCPU
          expr: rate(container_cpu_usage_seconds_total{pod=~"register-app-deployment-.*"}[5m]) > 0.4
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "Register App high CPU"
            description: "Pod {{ $labels.pod }} CPU usage is above 80%."
