apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: register-app-alerts
  namespace: default
  labels:
    release: monitoring    
spec:
  groups:
    - name: test-alerts
      rules:

        - alert: TestAlert
          expr: vector(1)
          for: 10s
          labels:
            severity: warning
          annotations:
            summary: "Test Alert Working"
            description: "Everything is configured correctly"
