apiVersion: apps/v1
kind: Deployment
metadata:
  name: register-app-deployment
  annotations:
    build-number: "4"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: register-app
  template:
    metadata:
      labels:
        app: register-app
      annotations:
        build-number: "4"
    spec:
      containers:
        - name: register-app
          image: khaledelnabawy1/register-app-pipeline:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
